spark.eventLog.enabled                 true
spark.eventLog.dir                     file:///tmp/spark-events
spark.history.fs.logDirectory          file:///tmp/spark-events
spark.sql.warehouse.dir                hdfs://namenode:9000/user/hive/warehouse
spark.hadoop.fs.defaultFS              hdfs://namenode:9000
spark.hadoop.hive.metastore.uris       thrift://hive-metastore:9083
spark.sql.catalogImplementation        hive
spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version 2
